// apps/api/src/utils/teamAliases.ts
// Keys and values are normalised (lowercase, no diacritics, no punctuation).
// Keys = post-normaliseTeamName API-Football names.
// Values = post-normaliseTeamName football-data.co.uk CSV names (the stored form).
// Add new entries whenever linkMatchStats.ts reports unmatched clubs.

export const TEAM_ALIASES: Record<string, string> = {
  // ── Portuguese ────────────────────────────────────────────────────────────
  'sl benfica':                  'benfica',
  'sport lisboa e benfica':      'benfica',
  'cf os belenenses':            'belenenses',
  'fc pacos de ferreira':        'pacos de ferreira',
  'gil vicente fc':              'gil vicente',

  // ── English ───────────────────────────────────────────────────────────────
  'manchester united':           'man united',
  'manchester city':             'man city',
  'tottenham hotspur':           'tottenham',
  'spurs':                       'tottenham',
  'newcastle united':            'newcastle',
  'brighton hove albion':        'brighton',   // & → removed by normaliseTeamName
  'brighton and hove albion':    'brighton',
  'sheffield united':            'sheffield utd',
  'wolverhampton wanderers':     'wolves',
  'west bromwich albion':        'west brom',
  'queens park rangers':         'qpr',
  'nottingham forest':           'nott m forest',
  'nottm forest':                'nott m forest',
  'luton town':                  'luton',
  'ipswich town':                'ipswich',
  'leicester city':              'leicester',
  'burnley fc':                  'burnley',
  'west ham united':             'west ham',
  'aston villa':                 'aston villa',

  // ── Spanish ───────────────────────────────────────────────────────────────
  'atletico de madrid':          'ath madrid',
  'atletico madrid':             'ath madrid',
  'athletic club':               'ath bilbao',
  'athletic bilbao':             'ath bilbao',
  'real betis balompie':         'betis',
  'real betis':                  'betis',
  'deportivo alaves':            'alaves',
  'rcd espanyol':                'espanol',
  'espanyol':                    'espanol',
  'rayo vallecano':              'vallecano',
  'ca osasuna':                  'osasuna',
  'ud almeria':                  'almeria',
  'girona fc':                   'girona',
  'rc celta':                    'celta',
  'rc celta de vigo':            'celta',
  'real valladolid':             'valladolid',
  'getafe cf':                   'getafe',
  'ud las palmas':               'las palmas',

  // ── German ────────────────────────────────────────────────────────────────
  'fc bayern munchen':           'bayern munich',
  'bayern munchen':              'bayern munich',   // API sends "Bayern München"
  'borussia dortmund':           'dortmund',
  'eintracht frankfurt':         'ein frankfurt',
  'bayer 04 leverkusen':         'leverkusen',
  'bayer leverkusen':            'leverkusen',
  'rasenballsport leipzig':      'rb leipzig',
  'borussia monchengladbach':    'mgladbach',       // CSV "M'gladbach" → "mgladbach"
  'vfl bochum':                  'bochum',
  '1 fc union berlin':           'union berlin',
  'fc union berlin':             'union berlin',
  'fc koln':                     'koln',
  'hamburger sv':                'hamburg',
  'hertha bsc':                  'hertha',
  'hertha berlin':               'hertha',
  'sv werder bremen':            'werder',
  'werder bremen':               'werder',
  'fsv mainz 05':                'mainz',
  'mainz 05':                    'mainz',
  'tsg 1899 hoffenheim':         'hoffenheim',
  'fc schalke 04':               'schalke',
  'schalke 04':                  'schalke',
  'sv darmstadt 98':             'darmstadt',
  'darmstadt 98':                'darmstadt',
  'fortuna dusseldorf':          'dusseldorf',
  'hannover 96':                 'hannover',
  'fc nurnberg':                 'nurnberg',
  '1 fc nurnberg':               'nurnberg',
  'karlsruher sc':               'karlsruhe',
  'holstein kiel':               'kiel',

  // ── Italian ───────────────────────────────────────────────────────────────
  'fc internazionale milano':    'inter',
  'internazionale':              'inter',
  'inter milan':                 'inter',
  'ac milan':                    'milan',
  'ss lazio':                    'lazio',
  'as roma':                     'roma',
  'ssc napoli':                  'napoli',
  'juventus fc':                 'juventus',
  'atalanta bc':                 'atalanta',
  'hellas verona':               'verona',
  'us sassuolo':                 'sassuolo',
  'udinese calcio':              'udinese',
  'cagliari calcio':             'cagliari',
  'bologna fc':                  'bologna',
  'acf fiorentina':              'fiorentina',
  'us lecce':                    'lecce',
  'empoli fc':                   'empoli',
  'torino fc':                   'torino',

  // ── French ────────────────────────────────────────────────────────────────
  'olympique de marseille':      'marseille',
  'olympique lyonnais':          'lyon',
  'paris saint germain':         'psg',
  'paris sg':                    'psg',
  'losc lille':                  'lille',
  'ogc nice':                    'nice',
  'rc lens':                     'lens',
  'stade rennais':               'rennes',
  'stade brestois':              'brest',
  'fc nantes':                   'nantes',
  'stade de reims':              'reims',
  'as monaco':                   'monaco',
  'as saint etienne':            'st etienne',
  'toulouse fc':                 'toulouse',
  'montpellier hsc':             'montpellier',
  'havre ac':                    'le havre',
  'le havre ac':                 'le havre',

  // ── Dutch ─────────────────────────────────────────────────────────────────
  'afc ajax':                    'ajax',
  'psv eindhoven':               'psv',
  'feyenoord rotterdam':         'feyenoord',
  'az alkmaar':                  'az',
  'fc twente':                   'twente',
  'vitesse arnhem':              'vitesse',
  'nec nijmegen':                'nec',
  'fc utrecht':                  'utrecht',
  'sc heerenveen':               'heerenveen',
  'roda jc':                     'roda',
  'fc groningen':                'groningen',
  'rkc waalwijk':                'waalwijk',
  'sparta rotterdam':            'sparta',
  'go ahead eagles':             'go ahead',
  'pec zwolle':                  'zwolle',
};

export function resolveAlias(normKey: string): string {
  return TEAM_ALIASES[normKey] ?? normKey;
}
