/// <reference types="nativewind/types" />

// NOTE: This file should not be edited and should be committed with your source code. It is generated by NativeWind.

// Allow CSS side-effect imports (used by NativeWind global.css)
declare module '*.css' {}